{
  "Brainrots": {
    "Divine": {
      "Bulbito Bandito Traktorito": 3000000,
      "Burgerini Bearini": 3500000,
      "Strawberry Elephant": 5000000,
      "Martino Gravitino": 4500000,
      "Galactio Fantasma": 8880000,
      "Grappellino D'Oro": 4750000,
      "Din Din Vaultero": 5500000,
      "Rubichetto Cubini": 8880000,
      "Glacierello Infernetti": 6000000,
      "Freezeti Cobretti": 9000000,
      "Biscotti Macarotti": 7500000,
      "Cupitron Consoletron": 9250000
    },
    "Infinity": {
      "Noobini Infeeny": 10000000,
      "Anububu": 15000000,
      "Meta Technetta": 25000000
    }
  },
  "MutationMultipliers": {
    "None": 1,
    "Emerald": 1.5,
    "Gold": 1.5,
    "Blood": 2,
    "Electric": 3,
    "Radioactive": 3.5,
    "UFO": 3.5,
    "Money": 3.888,
    "Candy": 3.95,
    "Gamer": 4,
    "Diamond": 4.25,
    "Admin": 4.5,
    "Hacker": 5,
    "Lucky": 8
  },
  "BaseSkins": [
    "Money Base Skin",
    "Glitch Base Skin"
  ]
}
